    name: Build and Push Docker Images

    on:
      push:
        branches: [ main ]
      workflow_dispatch:

    permissions:
      contents: read
      packages: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          # Step to copy entrypoint.sh before building 18
          - name: Prepare for Node.js 18 build
            run: cp entrypoint.sh 18/

          - name: Build and push Node.js 18
            uses: docker/build-push-action@v2
            with:
              context: ./18
              push: true
              tags: ghcr.io/ar4kiara/nodejs-pm2:18
              no-cache: true

          # Step to copy entrypoint.sh before building 20
          - name: Prepare for Node.js 20 build
            run: cp entrypoint.sh 20/

          - name: Build and push Node.js 20
            uses: docker/build-push-action@v2
            with:
              context: ./20
              push: true
              tags: ghcr.io/ar4kiara/nodejs-pm2:20
              no-cache: true

          # Step to copy entrypoint.sh before building 22
          - name: Prepare for Node.js 22 build
            run: cp entrypoint.sh 22/

          - name: Build and push Node.js 22
            uses: docker/build-push-action@v2
            with:
              context: ./22
              push: true
              tags: ghcr.io/ar4kiara/nodejs-pm2:22
              no-cache: true
